---
  extends:
    - react-app
    - eslint:recommended
  globals:
    mockFitnessAPI: readonly
    mockNutritionixAPI: readonly
    mountApp: readonly
    fillIn: readonly
    clickOn: readonly
    withStore: readonly
    API_VERSION: readonly
    _ : readonly
  parser: "@babel/eslint-parser"
  parserOptions:
    requireConfigFile: false
    ecmaFeatures:
      jsx: true
    ecmaVersion: latest
    sourceType: module
  ignorePatterns:
    node_modules
  rules:
    quotes:
      - 1
      - single
    jsx-quotes:
      - 1
      - prefer-double
    comma-spacing:
      - 1
      -
        before: false
        after: true
    space-in-parens:
      - 1
      - never
    no-restricted-imports:
      - 1
      - paths:
          - "@mui/material"
