# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.17.5
        environment:
          NODE_ENV: test
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            npm install --jobs=4 --retry=3

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "test/**/*.test.js" | \
              circleci tests split --split-by=timings)"

            npm test \
              --format progress \
              $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/repo/tmp/screenshots
          destination: screenshots
